name: Deploy to Shopify

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Shopify
        uses: shopify/shopify-cli-action@v1
        with:
          store: uburn.co
          theme-id: 181977973055
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_THEME_TOKEN }}
